language: php

# Sudo: false should make the builds faster, but collides with rabbitmq
sudo: true

php:
#  - 5.3
#  - 5.4
#  - 5.5
  - 5.6
#  - 7.0
#  - hhvm

env:
  # Test only on versions of Sf that are still supported
  - SYMFONY_VERSION=2.3.*
  - SYMFONY_VERSION=2.6.*
  - SYMFONY_VERSION=2.7.*

matrix:
  allow_failures:
    # at the moment it gives a core dump because of generation of code coverage...
    - php: 5.6

services:
  - rabbitmq

before_install:
  # This is mandatory or 'apt-get install' calls following will fail
  #- sudo apt-get update -qq
  # Install a custom Xdebug version, as the default one (2.2.7) crashes when generating code coverage
  - if [ "$TRAVIS_PHP_VERSION" = "5.6" ]; then pecl install xdebug; fi

install:
  - composer self-update
  # We might run composer install first, but then most of it would be undone anyway
  - composer require --prefer-source --dev symfony/process:${SYMFONY_VERSION} symfony/framework-bundle:${SYMFONY_VERSION} symfony/finder:${SYMFONY_VERSION} symfony/monolog-bundle:${SYMFONY_VERSION}

before_script:
  # Disable xdebug for speed.
  # NB: this should NOT be done for hhvm and php 7.0.
  # Also we use the php 5.6 run to generate code coverage reports, and we need xdebug for that
  - if [ "$TRAVIS_PHP_VERSION" != "hhvm" -a "$TRAVIS_PHP_VERSION" != "7.0" -a "$TRAVIS_PHP_VERSION" != "5.6" ]; then phpenv config-rm xdebug.ini; fi
  - if [ "$TRAVIS_PHP_VERSION" = "5.6" ]; then phpenv config-add Tests/travis/php.ini; fi
  - cp phpunit.xml.dist phpunit.xml

script:
  phpunit --coverage-clover=coverage.clover Tests/phpunit

after_failure:
  # Display as much info as we can to help developers
  - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php -i; fi
  #- cat apache_error.log
  #- cat apache_access.log
  #- cat /var/log/hhvm/error.log

after_script:
  # Upload code-coverage to Scrutinizer
  - if [ "$TRAVIS_PHP_VERSION" = "5.6" -a -f coverage.clover ]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [ "$TRAVIS_PHP_VERSION" = "5.6" -a -f coverage.clover ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi
  # Upload code-coverage to CodeClimate
  - if [ "$TRAVIS_PHP_VERSION" = "5.6" -a -f coverage.clover ]; then CODECLIMATE_REPO_TOKEN=TOBEGOTTEN ./vendor/bin/test-reporter --coverage-report=coverage.clover; fi

cache:
  directories:
    - $COMPOSER_CACHE_DIR
